### ISSUE TITLE
Add XR logo as favicon

### ISSUE THREAD

**Issue by aleesaan** [xrnl/aginun#100]
## Feature description
Shall we add a favicon? We could use [this one](https://base.extinctionrebellion.nl/uploads/default/optimized/1X/e835115983645fce791bbfe2e8c845e3e8d79a2d_2_32x32.png) maybe?

**Comment by SamLubbers** [comment]
@aleesaan we do indeed still need to add a favicon. You can add the one you shared :ok_hand:
