### ISSUE TITLE
Upgrade to Vue3

### ISSUE THREAD

**Issue by RainnyX** [xrnl/aginun#113]
## Problem that this feature solves
To future proof this project and to fully support typescript with the new composition api, a upgrade to Vue3 is needed.

**Comment by aleesaan** [comment]
I'm afraid we will have to wait for this, as vuetify does not support vue 3 - [they expect vuetify 3 to be done next summer](https://vuetifyjs.com/en/introduction/roadmap/). Still, I would migrate to typescript already, and upgrade to vue 3 once it's more stable ([as they also are working on a migration build](https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes)). What do you think?

**Comment by RainnyX** [comment]
Fully agree, already busy integrating typescript ;)

**Comment by SamLubbers** [comment]
Woops, I accidentally just made a duplicate of this issue #186. I'll keep the other one as it contains information about the dependencies to other issues that need to be implemented first.
