### ISSUE TITLE
Store auth token in front-end

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#122]
## Problem that this feature solves
Right now if a user logs in, the authentication token is stored in the Vuex state. If the user closes the window or refreshes the page, this state is gone and the user needs to login again.

## Feature description

Describe a step-by-step use case of your feature. 

1. The token should be stored in local storage (cookie) after logging in
2. The token should be retrieved from local storage. If it exists the token should be set in the Vuex store, if it doesn't exist the user should not be logged in.

## Additional comments
Tokens have a lifetime, depending on settings in the KeyCloak keyserver. It would be best to have the token in the local storage expire after the lifetime of the token has passed, as the token won't work for requests anymore. Another option would be to invalidate the local storage if a request to the Hasura server fails because of an invalid/expired token, and thus have the user login again.

**Comment by tomootes** [comment]
@aleesaan the issue im doing right (#130 ) is depending on this one. I found this tutorial which might be helpful: https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#basics_client_setup_expiration

Right now when i want to connect to Hasura using a token from Keycloak i get the error: `Could not verify JWT: JWTExpired`. Maybe we can have a quick call about this? It all seems quite connected.
