### ISSUE TITLE
Internal-only roles

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#128]
## Problem that this feature solves

For some roles that require high levels of experience and responsibility, rebels want to find other people that already have some level of experience in the movement, and not someone who wants to get involved for the first time.

### Publishing a role

1. When creating the role, user ticks the checkbox saying "internal only role". See ideas for how to implement this in #98 and #116 

### Finding a role

1. Volunteer goes on to the platform and they only see roles that are not internal only
2. Volunteer logs in with their account
3. Now the role overview page shows all roles, including internal roles.

### Viewing a role

When the volunteer is viewing an internal only role, under the requirements list they should see an indication that this role is only for people already involved in XR. The interface for this could be similar to how Airbnb and hotel websites show requirements fulfilled by a certain accommodation.

## Additional comments

There is also a reason why this feature shouldn't be implemented. An "internal only" indication is very vague and doesn't define any information about what kind of experience is required & how long someone had to be involved. People could also define this requirement as text in the current `requirements` field. Then volunteers would see all roles, but they just wouldn't apply for roles for which they don't meet the requirements.

**Comment by CoenHolten** [comment]
I agree on the additional comments.
Defining internal and external also includes judgement:
While defining 'internal' and 'external', and each time a rebel is allowed to see the internal vacancies..

I believe judgment is at the basis of power structures, and is opposing inclusiveness.
Moreover, is it smart to refuse any volunteer if we want to grow?
I understand the need for experienced rebels, but if someone believes she/he is that, I think we should accept that in gratefulness, and not put our selves above it.
(if no spiritual/philosophical/ethical input/reflecting here is appreciated, please let me know :)  and I will let go of it)

**Comment by SamLubbers** [comment]
Thanks for your comments Coen. I will indeed close this issue, not only because of the concerns you mentioned, but also because it will greatly increase the complexity of our authorization system. We will just use the volunteer platform for public roles. For very important internal roles we can continue using our existing method: 1 to 1 recruitment via direct messages.
