### ISSUE TITLE
Add information about organisational structure & groups

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#138]
## Problem that this feature solves

Currently we use the "local group" and "working circle" terms to filter roles, but many new people to the organisation do not know what those terms mean, and what their relation is. Explaining these terms, and how they relate to the organisational structure will make it easier for people to find a role and understand their place in the movement.

### Structure page

1. User navigates to the /structure page from the navigation bar. 
2. User is able to read about our structure: why we are structured as decentralised circles, what local groups are and what working circles are.
3. User can read in detail about what each working circle does.
4. Users can see navigate to the list of local groups on the [XR NL website](https://extinctionrebellion.nl/lokale-groepen/)
5. Users can see a visual overview of our structure. We could embed [the diagram on this page](https://extinctionrebellion.nl/structuur/)

### Information throughout the application

Users should also be able to access this information while navigating through the application. Some ideas are

- next to the filters there can be a popup/text directing them to the structure page for more info
- next to each mention of a local group or working circle, such as in filters, an individual role view or in the form to create/edit a role. Users should be able to easily read what the terms "local group" & "working circles" mean, and a description of what the each working circle does.

### Additional comments

If this is too much work for one issue feel free to split this up into separate smaller issues.

**Comment by SamLubbers** [comment]
@kajdehoop and Laura are making a great design for this page. It will be best to wait for the design and implement it once it's ready

**Comment by SamLubbers** [comment]
Some suggestions from previous meetings:

- perhaps it would be good to have this information in an `about` page, where we also explain the platform and how it's used.
- when people visit the website for the first (few) times an animation directs them to this page.

**Comment by SamLubbers** [comment]
The design for the new about page can be found here: https://zeroheight.com/4eba4d3a1/p/063c65-about/b/407259

**Comment by CoenHolten** [comment]
Is there a way to integrate this map: https://rebellion.global/groups/#countries
With the Netherlands in focus.
And link info of the groups to pin ons the map?

**Comment by CoenHolten** [comment]
And maybe visualize relations between working circles..
And allow more freedom in the purpose of working circles.. 
like for instance a multi dicipline working circle on a certain action.
and show contact persons and active roles per circle, when clicking them

**Comment by SamLubbers** [comment]
> Is there a way to integrate this map

We used to have this on the XR NL website but we decided to remove it in favour of a complete list with more information: https://extinctionrebellion.nl/lokale-groepen/

> Is there a way I contribute to this project without being a programmer?

For sure! These sort of questions are best discussed outside of a specific issue. You can send me a message on Mattermost :innocent:

**Comment by CoenHolten** [comment]
Maybe for future:
1) It could be an idea to consider "working circles" as "communities/rebel pools" where people with certain skill gather, exchange knowledge, and can be found.

2) And open an option to categorize circles to the "parts of our mission" they are acting on.
- direct action
- social justice
- showing alternatives
- movement of movements
(and the sub missions of these main missions)

3) And add "XR families" as a category for circles position in the movement

Ideally (that's my personal believe) these communities, mission related groups, and families could have their own MatterMost Team, to organize their channels and gather rebels that want to be active in that area of XR.

**Comment by CoenHolten** [comment]
[XR Treemap.xlsx](https://github.com/xrnl/aginun/files/6617742/XR.Treemap.xlsx)

Started this treemap to map all activity in xr. But did not finish it because other things got higher priority

**Comment by SamLubbers** [comment]
Hey Coen, I would appreciate if you can keep the discussion in each issue relevant to that issue. For ideas about information or group management in XR you should contact or join the relevant working circle

**Comment by aleesaan** [comment]
Closed in #214.
