### ISSUE TITLE
Backend documentation

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#151]
## Problem that this documentation solves

People who join the project and work on the backend of the project find it difficult to understand how the frontend interacts with the various backend systems.

## Description

Make a new wiki page where we explain each of the backend systems: why we use them, what they do, how they interact with each other, and how to access and edit each of them.

The list of backend systems that we have are:

* Hasura: PostgreSQL database + GraphQL API. Used to store user created data such as roles, groups and more
* Keycloack: Authentication server. Used for logging in users.
* Loco: used to manage translations.

## Additional comments

After making the wiki page do not forget to add it to the wiki table of contents :books:

**Comment by tomootes** [comment]
@SamLubbers i added a small section called `Authentication Flow` to the Wiki: https://github.com/xrnl/aginun/wiki/Architecture. Lets discuss this tomorrow.

**Comment by SamLubbers** [comment]
@tomootes thanks for writing this clear documentation so quickly :green_heart: The text you've makes it very easy to understand how the authentication works. With this info + the new [internationalization](https://github.com/xrnl/aginun/wiki/Internationalization-(i18n)) page that Ale created we can close this issue :heavy_check_mark: 

If the authentication documentation expands then we can turn it into it's own wiki page, and link to it from other wiki pages, or the contributing guidelines.

**Comment by SamLubbers** [comment]
@tomootes thanks for writing this clear documentation so quickly :green_heart: The text you've makes it very easy to understand how the authentication works. With this info + the new [internationalization](https://github.com/xrnl/aginun/wiki/Internationalization-(i18n)) page that Ale created we can close this issue :heavy_check_mark: 

If the authentication documentation expands then we can turn it into its own wiki page, and link to it from other wiki pages, or the contributing guidelines.
