### ISSUE TITLE
Easily clear individual filters

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#16]
Two minor improvements to make it easier to clear individual filters:

1. Clear search: When the user types in the text in the search field a cross button should appear. When the user clicks that button the search field is cleared & the search filter is removed.
2. Clear filters: Currently, selected local groups or working groups appear as chips within the search field. It would be useful if these chips contain a small cross to de-select a given local group or working group. See an example [here](https://vuetifyjs.com/en/components/autocompletes#slots)

Once this issue is resolved the use case [#4: finding a role](https://github.com/xrnl/aginun/wiki/Functional-Specification#4-finding-a-role) will be completed.

To avoid conflicts, it is best to resolve this issue after merging #12

**Comment by aleesaan** [comment]
I'm closing this issue as it looks done to me! @SamLubbers correct me if I'm wrong :)
