### ISSUE TITLE
Show circles on about page

### ISSUE THREAD

**Issue by tomootes** [xrnl/aginun#161]
In the new designs a view for exploring the circles is created:

![Schermafbeelding 2021-05-21 om 11 19 05](https://user-images.githubusercontent.com/4222167/119114445-763a7c00-ba26-11eb-953e-aa72d8ada60b.png)

# Function
A view like this will make it easier for people to explore the structure that XR has

# Structure
In the research for this feature i've stumbled upon this page: https://extinctionrebellion.nl/structuur/. Isn't this quite similar?

**Comment by CoenHolten** [comment]
https://observablehq.com/@d3/zoomable-circle-packing

**Comment by CoenHolten** [comment]
I did a lot of thinking about this. Maybe somebody of aginun wants to know a bout it.

**Comment by SamLubbers** [comment]
@tomootes I'm closing this issue as it's a duplicate from #138 :ok_hand:
