### ISSUE TITLE
Implement design: Role info modal

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#168]
This is the modal that's shown when a role card is clicked in the Overview page (#167 )

[Link to design](https://zeroheight.com/4eba4d3a1/p/79fb2a-role-info/b/407259)

[Link to illustrations used in the design](https://zeroheight.com/4eba4d3a1/p/80374f-illustrations)

**Comment by SamLubbers** [comment]
@kajdehoop when you create new smaller issues for this page remember to also consider the view for logged in users. For example, one of the issues that we need to make is to remove the "role taken" button (and all the functionality associated to it, including tests.)

**Comment by kajdehoop** [comment]
I've added some smaller sub issues for this modal. Keeping this issue as an overall styling issue. Can be closed when the modal matches the design

**Comment by aleesaan** [comment]
Implemented in #224.
