### ISSUE TITLE
Implement design: My Roles page

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#170]
This is the page that a Rebel (in most cases an integrator or coordinator) will see when logged in

[Link to design](https://zeroheight.com/4eba4d3a1/p/36913e-my-roles/b/407259)

[Link to illustrations used in the design](https://zeroheight.com/4eba4d3a1/p/80374f-illustrations)

**Comment by SamLubbers** [comment]
@kajdehoop this is a duplicate of #162 no? You can decide whether to close this issue or that one :)

**Comment by kajdehoop** [comment]
I've added the designs to #162 and will close this issue 👍
