### ISSUE TITLE
Implement design: Edit/New Role modal

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#171]
This is the modal that shows up when a Rebel adds a new role or edits a role in the My Roles page (#170). The New Role modal and Edit Role modal are basically the same, the only difference is the buttons on the bottom: the New Role modal has a 'Create' button, the Edit Role modal has a 'Save' and a 'Cancel' button.

[Link to design](https://zeroheight.com/4eba4d3a1/p/863731-editnew-role/b/407259)

**Comment by aleesaan** [comment]
Closed in #224.
