### ISSUE TITLE
Implement design: About page

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#173]
Main purpose of this page is explaining what XR is and how it is structured. The design of the interactive element explaining the structure is not final yet, might change in the future. The general layout of this page is finished however.

[Link to design](https://zeroheight.com/4eba4d3a1/p/063c65-about/b/407259)

**Comment by SamLubbers** [comment]
I think part of this issue is specified in #138 You can decide which issue to close and which one to keep :ok_hand:

**Comment by kajdehoop** [comment]
I'll close this one 👍
