### ISSUE TITLE
Show all roles within time commitment range

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#179]
## Steps to reproduce the problem

1. Apply the "time commitment" filter. For example, set the minimum time commitment to 9 hours and the maximum to 30 hours.

## Expected result after following these steps

The application displays any roles with a maximum time commitment above 9 hours and a minimum time commitment below 30 hours. So a role with a time commitment of 6-10 hours is also displayed.

## Actual result

The application displays any roles with a minimum time commitment over 9 hours and a maximum under 30 hours. So a role with a time commitment of 6-10 hours is NOT displayed. 

## Additional comments

I just realised that this only requires 2 lines to change in `src/GraphQL/roles.ts`:

```
          { timeCommitmentMin: { _gte: $timeCommitmentMin } }
          { timeCommitmentMax: { _lte: $timeCommitmentMax } }
```

**Comment by ShubhamPalriwala** [comment]
Hey @SamLubbers, I would like to fix this small bug!
Please provide me the Development API Key so that I can fix it as early as possible!

**Comment by SamLubbers** [comment]
Hey @ShubhamPalriwala I'm so glad to hear that you want to pick up this issue! And sorry I didn't see your comment before (I had email notifications disabled for a while)

The application doesn't use a development API key anymore. So you should be able to clone the code, run it and get it working straight away!
