### ISSUE TITLE
Navbar: Change text and logo to correct colors 

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#190]
#fff for text and logo, #14AA7D for background

[Link to design](https://zeroheight.com/4eba4d3a1/p/5611c9-navbar/b/0329b7)

**Comment by aleesaan** [comment]
Closed in https://github.com/xrnl/aginun/commit/56823b92924aed88e76c7768b63ed22420c0d1aa.

**Comment by SamLubbers** [comment]
@aleesaan thanks for the change! Next time you could even close the issue directly from the commit (by adding a [closing keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in the commit message :smirk: )
