### ISSUE TITLE
Navbar: Remove borders from login button & left-allign navigation buttons

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#193]
Login should look the same as the other buttons. [Link to design](https://zeroheight.com/4eba4d3a1/p/5611c9-navbar/b/0329b7)

**Comment by aleesaan** [comment]
Heya, I think it's actually good to keep the login button different: the other buttons in the navbar are navigation links, while the login is a button that does something. I think the same applies to [this issue](https://github.com/xrnl/aginun/issues/191) about the language dropdown - I don't particularly like the dropdown we have, but I do think we should make the language selection stand out, to show a difference with the rest of the navigation links / login button. What do you think?

**Comment by SamLubbers** [comment]
Good point @aleesaan it might be confusing if we have buttons with different functionality in the exact same style in the same navigation menu. We can keep the border (like we have now), or we can keep Kaj's style and move the navigation buttons to the left of the navbar. Just like github.com has.

**Comment by kajdehoop** [comment]
I would keep the design style, but move the navigation buttons to the left, as Sam said :)

**Comment by aleesaan** [comment]
I moved the navigation buttons to the left as agreed, but also left the login button with an outline as I think it's good to differentiate it - especially on mobile, where the nav is more compact.

It looks quite good I think! Have a look here:

https://user-images.githubusercontent.com/42735629/141654191-b03b3cba-c327-4a2b-8efe-255d91ac3567.mov

**Comment by kajdehoop** [comment]
Yes looks good! :)
