### ISSUE TITLE
add NVM configuration to always have the correct Node version

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#231]
## Problem that this feature solves

The application might not work as expected if users have the wrong version of Node installed. 

## Feature description

Add NVM configuration, so that the right version of Node is always used.

## Additional comments

I have no idea what I'm saying, but @aleesaan said he could easily take care of this :sweat_smile:

**Comment by aleesaan** [comment]
Closed in [this commit](https://github.com/xrnl/aginun/commit/5a95d635d4d58dc90668b5cba66a871a63f434f9).
