### ISSUE TITLE
authorization: restrict user edit/delete permissions

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#237]
At the moment, you can edit or delete the roles created by other users. We need to fix this on the frontend and backend:

- on the backend, we need validation, checking that users can only edit and delete the roles that they've created.
- on the frontend, we should hide the edit and delete button for roles that do not belong to that user

**Comment by aleesaan** [comment]
This got closed with your PR, but since I'm already handling the frontend part in this [PR](https://github.com/xrnl/aginun/pull/250), we can keep it closed :v:
