### ISSUE TITLE
correct support contact & information

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#240]
currently we have `@vacancies_support_xrnl` as the account where people can ask questions. This is not ideal as this account is no longer maintained, and only one person has access to that account. It would be better to link to the [public volunteer platform channel](https://organise.earth/xr-netherlands/channels/volunteer-platform). That way people can see each other's questions, and anyone in the team can answer those questions. 

The same applies for the login view. Currently, we ask people to send us an email if they want an account. It would be better if they send a message in the volunteer platform channel

On the support page, we say people can contact the `welcome@extinctionrebellion.com` email for "more general questions". I see two issues: 1. it's not clear when to contact the email and when to send us a message on Mattermost 2. contacting the general email might not be the best backup option if people cannot find a role. I think we can leave this out for now, and properly take care of it in #219.

**Comment by SamLubbers** [comment]
@aleesaan I see that say you resolved part of this in #184, but I think the vacancies support account is still there in the support page :thinking:

**Comment by aleesaan** [comment]
It should be good now 👌  maybe double check it's ok?
