### ISSUE TITLE
fix all vulernabilities

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#243]
When I run `npm audit` I get `77 vulnerabilities (57 moderate, 20 high)`

Some we can fix automatically with `npm audit fix`. Others we'll have to resolve manually

**Comment by aleesaan** [comment]
I found a bunch of SO threads trying to figure out how to solve it, but apparently it's a known issue with vue-cli packages, as mentioned in [this thread](https://stackoverflow.com/questions/61864753/how-to-fix-vue-cli-service-vulnerability).  
  
Running `npm audit --production` finds no vulnerabilities, so I think we're good, at least until they fix the vue cli stuff.
