### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#38]
See: [Setting guidelines for repository contributors](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

Some of the things we want to specify in our contributing guidelines:
* Document that we will use Fork and Pull model over shared repository model. Learn about these models [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-collaborative-development-models)
* How people can make a new request: open an issue and assign the `suggestion` tag
* Pull request standards.
* We use of Prettier instead of a style guide. All code should be automatically formatted with Prettier.

**Comment by abudaan** [comment]
Could it be that the code in the master branch isn't well formatted?
1. clone master to new folder
2. run `npm i`, `npm audit fix` and `npm run serve`
3. this yields 25 prettier errors, most of them are missing trailing , and ;

**Comment by SamLubbers** [comment]
That is correct. I'll resolve this issue (#28) soon.

**Comment by SamLubbers** [comment]
The first version of the contributing guidelines is [done](https://github.com/xrnl/aginun/blob/master/CONTRIBUTING.md).
