### ISSUE TITLE
Dutch + English support

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#39]
Right now English is the only supported language. We need to also support Dutch as XR NL is a Dutch movement. 

In addition to being able to change the text of the application, the user should also be able to:
* add roles/tasks in both dutch and english. This should be an option but should not be required. Users can still add roles/tasks in just dutch or just english.
* see roles/tasks in the language that they have selected
* if there are roles/tasks not written in the selected language, the user should get an indication of this when browsing.

**Comment by kajdehoop** [comment]
We can use Vue i18n for translations of texts in the UI. We can combine this with Loco (https://localise.biz/) and get the updated translations from that API with gulp during the build process.

**Comment by SamLubbers** [comment]
@kajdehoop that sounds good :ok_hand: I would also look into [Vuetify's i18n](https://vuetifyjs.com/en/features/internationalization/#getting-started) so translations work well with existing components.

In addition to translating fixed text, we also need to make sure that users provide all role information in both english and dutch (role description, responsibilities, requirements...). In addition, users should also be able to mark a role as only for dutch speakers. This role should then only appear in the dutch page but not in the English page.

**Comment by SamLubbers** [comment]
@aleesaan you had experience with translations right? Would you like to work on this issue?

**Comment by aleesaan** [comment]
I could give it a try, but to be honest I'd rather pick up smaller cases to get familiar with vue first. I think also kaj has experience with this, do you think you could pick it up @kajdehoop? If we don't do it all at once I could try to work on smaller parts of it perhaps; I'd also be happy to share some high-level ideas anyway!

**Comment by kajdehoop** [comment]
Yes I can look into this issue ;) Maybe it should be split into two separate issues. We can use Vue i18n for the interface translations, but this is a separate issue from adding translation fields for the role information.

**Comment by aleesaan** [comment]
Awesome! Indeed I could then pick up the other part, to update the role info with translation objects. For the multilingual input, I think we could use a field with an icon (maybe a flag?) on the side, to toggle the language or perhaps show another input below, with the other language. Just a thought, we can also discuss better later!

**Comment by SamLubbers** [comment]
@kajdehoop Good idea to split this into two separate issues. I just made the other one here: #103 

@aleesaan good to know you'd rather work on smaller issues first. I've assigned you to issue #103, but this is too much to start with you can always look at other smaller features.

**Comment by kajdehoop** [comment]
Note from the meeting: the cost of the translation service will be researched by @aleesaan

**Comment by aleesaan** [comment]
I think the free plan from Loco is good enough, you can see more info [here](https://localise.biz/plans). It can have up to 1000 strings (it says 2000 cause you can have two projects, but we only need one), and unlimited translators, which sounds perfect to me!  
What do you guys think @kajdehoop and @SamLubbers?

**Comment by kajdehoop** [comment]
@aleesaan Sounds good! ^^

**Comment by SamLubbers** [comment]
@aleesaan the free plan sounds ideal for our current use case! But it's also always good to see what we would have to pay if we ever exceed the freemium model. Some companies lure you in with free services and before you know it you have to start paying a lot to continue using their services.

I checked the link that you shared and even if we have 25,000 translations it's only 20€ per month. That's definitely something XR can afford, so it's good to proceed with Loco 👌

**Comment by aleesaan** [comment]
Ahah yea I doubt we'll get to 25k translations, we currently have less than 100 😛 let's go for it!

**Comment by aleesaan** [comment]
Closing this as it was already implemented in [this PR](https://github.com/xrnl/aginun/pull/141).
