### ISSUE TITLE
Setup authentication

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#41]
We need Authentication so that not everyone can create, edit, and delete roles & tasks. To limit these functionalities to local groups & working groups in XR, we will issue pre-created accounts to these groups. 

### subtasks
1. Chose an authentication service: We need such a service [authentication is handled outside of Hasura](https://hasura.io/docs/1.0/graphql/manual/auth/index.html)
2. Setup authentication service: Hasura supports [two authentication methods](https://hasura.io/docs/1.0/graphql/manual/auth/authentication/index.html): Webhooks or JWT tokens. We have been advised that: "if you want to get moving fast, the webhook looks much simpler. However, each requests received by Hasura will fire a request to the webhook as opposed to a single JWT token request which is then passed with each requesst. So that's probably something for later on when / if you see performance issues"

**Comment by kajdehoop** [comment]
I don't have experience with JWT specifically, but I have some experience with token-based authentication. I think it would be best to use the JWT tokens with [Auth0](https://auth0.com/pricing/) They have a free plan up to 7.000 users. As we would probably only need logged-in users for adding new roles & tasks I think that would be sufficient. They also have a [program for non-profit organisations](https://auth0.com/social-impact/nonprofits), so maybe the user limit won't be a problem at all. If we follow [this guide](https://hasura.io/blog/add-authentication-and-authorization-to-vue-js-apps-with-auth0-graphql/) it shouldn't be too hard to implement the authentication & authorization.

**Comment by SamLubbers** [comment]
@kajdehoop great that you have experience with token-based authentication. I looked at Auth0 some time ago but I found the following issues:
  * we cannot self host it: In XR we'd like to self-host all our applications so that we remain in control of user's data.
  * it's too expensive: it's true that now we will only need accounts for people that create roles, but in the future we might also need accounts for volunteers. If this applications ends up being used by XR groups around the world we could easily surpass their free limit of 7000 users. Even with the non-profit discount it can become too expensive. 

An alternative Authentication solution could be [Keycloack](https://www.keycloak.org/), as we can self-host it and has [OAuth-2 support](https://www.keycloak.org/docs/latest/server_admin/), meaning users might be able to sign-in with the log-in they already have for Mattermost, our internal communication platform. 

I have found [this keycloack-Hasura connector](https://httpsomkar.github.io/keycloak-hasura-connector/). Would you like to look into making this authentication configuration work?

**Comment by kajdehoop** [comment]
Alright! I'll look into the authentication by using Keycloak next weekend :)

**Comment by SamLubbers** [comment]
@kajdehoop were you able to look into authentication already? If you haven't I highly encourage you to get in contact with Felix (@unkown on Mattermost) as he has experience with setting up keycloack and he could be of great help here :muscle:

**Comment by kajdehoop** [comment]
I was busier than expected last weekend, but I've send Felix a message on Mattermost :)
