### ISSUE TITLE
Task creation

### ISSUE THREAD

**Issue by JBuma** [xrnl/aginun#5]
Implement all steps for the use case [#3: creating a task](https://github.com/xrnl/aginun/wiki/Functional-Specification#3-creating-a-task), except for the steps that require user authentication.

This issue can be easily completed once #1 is done.

**Comment by SamLubbers** [comment]
We should minimise code duplication with the same functionality for roles. To achieve this we can: 1. Duplicate the existing role component
2. Edit the code so to fit tasks.
3. Abstract into a base component the code that can be shared between tasks and roles.
4. Have the role and task component inherit from the base component.
