### ISSUE TITLE
easier clearing of filters

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#55]
The following improvements will make it easier for the user to clear filters, and therefore to find roles.

### Search
Currently, when a user wants to remove their search term they need to eliminate all characters one by one.

An easier approach, is that when a user types text into the search bar, a small cross icon appears in the search field. When the user clicks that icon, all text is cleared and the icon disappears.

### Local group and working circle filters
Currently, when a user wants to remove a selected working group or local group, they need to click the input field, scroll down the list of groups and deselect the desired one. 

An easier approach, is that when a user selects a local group or working circle, a small cross icon appears next to the working group or local group name. See an example [here](https://vuetifyjs.com/en/components/combobox/#advanced-custom-options). When a user clicks on the cross, the group should be deselected.

**Comment by kajdehoop** [comment]
I'm picking up this issue :)
