### ISSUE TITLE
Task overview list

### ISSUE THREAD

**Issue by JBuma** [xrnl/aginun#6]
Users need to be able to see a list of tasks and filter them to find one they want to work on.
Basically the same thing as the existing role overview, but for tasks.
Filters needed:

- Text search (Search in description, title, location)
- Group filters (Local groups, working groups)
- Time commitment
- Location

Task cards have the following info, clicking on them will bring you to the task detail view:
- Title
- Local and working Groups
- Time commitment
- Button to view the detail page

**Comment by SamLubbers** [comment]
To be completed after merging #12, when the overview and search of the role are linked to the backend.

**Comment by SamLubbers** [comment]
We should minimise code duplication with the same functionality for roles. To achieve this we can: 1. Duplicate the existing role component
2. Edit the code to fit tasks.
3. Abstract into a base component the code that can be shared between tasks and roles.
4. Have the role and task component inherit from the base component.

**Comment by abudaan** [comment]
I clone your fork and checkout the task-overview branch. Then when I run `npm i` and `npm run serve` it yields a massive amount of errors and warnings from prettier/prettier.
