### ISSUE TITLE
Add group colours to the cards

### ISSUE THREAD

**Issue by tomootes** [xrnl/aginun#76]
## Problem that this feature solves
It's hard to distinguish the different groups within the cards shown at a glance. Adding colours makes this easier.

## Feature description
To solve this we want to add colours to the cards.

## Additional comments
Some of the themes can be drawn together with the same colour.

Outreach / training can go together as a colour.
Rebellion support / coordination circle  can go together as a colour.
Political strategy en future democracy can go together as a colour.

All the groups can be found here:
https://docs.google.com/forms/d/e/1FAIpQLSdIabp3sec0mgTClLctp4VPxjsaghAK6e_PyTlwrxM4i2eWug/viewform

Two examples of the colours used can be found here:
- https://rebellion.global/news/#blog
- https://www.onlinevolunteering.org/en/opportunities

**Comment by tomootes** [comment]
The colours chosen for the groups are:


1. Action & Logistics : khaki
2. Arts in Action: red
3. Finance: navy
4. Inclusion & Power: yellow
5. Integration: lemon
6. Legal: navy
7. Media & Communications: red
8. Outreach & Training: purple
9. Political Strategy & Change: green
10. Regenerative Culture: yellow
11. Tech: blue
12. Rebellion Support Circle: purple
13. Coordination Circle: purple
14. Future of Democracy: green

**Comment by SamLubbers** [comment]
@tomootes sounds good to me! Once we have roles published for the different groups we'll see what adjustments we need to make 👌

**Comment by SamLubbers** [comment]
This was implemented a long time ago in #77
