### ISSUE TITLE
Email/message notifications of new available tasks based on filters

### ISSUE THREAD

**Issue by reinvdwoerd** [xrnl/aginun#81]
## Problem that this feature solves
Without notifications, people looking for a task or role would need to check the website often to not miss it.

## Feature description
Allow people to subscribe to email/message notifications for when a new task or role within a specific group or region (example: the Arts group of XR Alkmaar) becomes available.

Describe a step-by-step use case of your feature. 

1. 
2. 
3.

**Comment by SamLubbers** [comment]
We'll close this for now because we don't plan to have tasks any time soon
