### ISSUE TITLE
Page title shows filters for working circle and local group in readable form

### ISSUE THREAD

**Issue by reinvdwoerd** [xrnl/aginun#82]
## Problem that this feature solves
A title of just 'Aginun' isn't very informative when sharing a link to  in chat apps.
Showing something like 'Positions for Outreach & Training in XR Alkmaar' in the title would immediately let people know what the page is about.

## Feature description

Describe a step-by-step use case of your feature. 

1. 
2. 
3.

**Comment by SamLubbers** [comment]
This was fixed with the new navbar :ok_hand:
