### ISSUE TITLE
Setup basic user-side navigation

### ISSUE THREAD

**Issue by JBuma** [xrnl/aginun#9]
We will be supporting both tasks and roles in the first release, and we want them to be in separate lists to keep them distinct. Basic structure will be something like:

**Homepage:** {base_url}
**Task overview:** {base_url}/tasks
**Task detail:** {base_url}/tasks/{task_id}
**Task create:** {base_url}/tasks/new

Same thing for roles. Since this will be a Single Page Application (or SPA), navigation will take place on the frontend using [VueRouter](https://router.vuejs.org/). This is already installed and set up so you can get going immediately.

**Comment by abudaan** [comment]
Okay, and then only {base_url}/tasks/new requires authentication / authorization?

**Comment by SamLubbers** [comment]
@abudaan that is correct.

**Comment by SamLubbers** [comment]
A few additional questions to answer about the URL structure:

In the (long term) future we aspire other national XR branches to also use this platform to manage their roles & tasks. To easily support this we should have the country code as the first element in the URL structure `{base_url}/{country_code}`. For example, for this first version only used in The Netherlands, we will have `{base_url}/NL`, `{base_url}/NL/tasks `...

In this version, the home page will be the role overview page. However, in the future, we might want a different home page. Either a global page where you can navigate to the pages of different countries, or a home page where users can see their roles / tasks. To support this we should keep clear the base URL: when users navigate to `/` they will be immediately redirected to `/roles`

**Comment by SamLubbers** [comment]
### international URL
In the previous comment, where I talked about other countries also making use of this application, I had assumed that they would all host their roles in the same website, for example, on `xrvolunteer.com`. However, having all countries make use of a single domain has several problems:
  * security: if this single domain is brought down, the applications stops working for all countries
  * scalability issues: if the application is used worldwide, we must put in extra work for the application to scale properly, so it works fast wherever it is used.
  * energy use: transmitting data over larger distances requires more energy.

An improved alternative solution, is for each country to self-host their own version of the application. So the XR NL platform could be hosted on `volunteer.extinctionrebellion.nl` and the XR US platform could be hosted on `volunteer.extinctionrebellion.nl`. 

With this configuration, we don't need the country code in the URL, like I mentioned in the previous post.

### home page redirect
In the previous post I also mentioned redirecting from `/` to `/roles`. However, we will integrate roles and tasks into the same page, so we could instead redirect to `/explore`, where both roles and tasks will be displayed.

**Comment by SamLubbers** [comment]
Following up on my previous comment, even thouhg we do not need the country in the URL in order to search for roles in that country, we do need some argument in the URL to get the page in a certain language (NL/EN). @aleesaan how do you recommend including a language identifier in the URL? :thinking:

**Comment by aleesaan** [comment]
> how do you recommend including a language identifier in the URL? 🤔

I don't think we should! SPAs don't really show languages in the URLs - it made more sense for older sites, or generally static ones where a full page-refresh is needed to change language. I already added [an automatic initialization of the right language when we create the app](https://github.com/xrnl/aginun/blob/master/src/main.ts#L20), and if for some reason your browser's language isn't correct, you can easily change it in the app.

**Comment by SamLubbers** [comment]
@aleesaan good to know that SPAs don't need a language identifier in the URL, and that they can load the correct language from the browser language. I didn't even know that was possible :scream:

**Comment by aleesaan** [comment]
Can we close this issue @SamLubbers?

**Comment by SamLubbers** [comment]
@aleesaan yes! The URL structure that we have now is good as it redirects users to `/roles` in case we want to use the home url `/` for something else in the future.
