### ISSUE TITLE
Add padding to popups

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#92]
## Problem that this feature solves
The popup modal feel a little cramped right now

## Feature description
Add some padding to the popups, so they look better

**Comment by SamLubbers** [comment]
@kajdehoop for improvements to the UI could you provide some screenshots? It would be useful to visualize the problem so it's easier to know how to fix it. For such a small issue you could actually directly make a pull request with the before and after pictures :ok_hand:

**Comment by SamLubbers** [comment]
Closing this issue as it's not been merged in #101 and it's not a crucial functionality. We'll adjust this CSS once we've finalised the new designs for the interface.
