### ISSUE TITLE
Add a drop shadow when hovering over the role cards

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#94]
## Problem that this feature solves
It can be unclear that the role cards are completely clickable

## Feature description
We can add a drop shadow when a user hovers over a role card. (Maybe we can then even remove the 'Read more' button as it's clear that the cards are clickable, but this is debatable as the mobile website will not have a hover effect anyway)

**Comment by SamLubbers** [comment]
@kajdehoop I agree that adding a drop shadow on hover makes it clearer that the card is clickable. That's actually how it used to work, but it was removed by Tom in #77 to keep it consistent with the design of [XR global](rebellion.global/).

If you think it would be good to add it back, all you need to do is add `:elevation="hover ? 12 : 2"` as a property of `v-card` in `DeafultCard` :sparkles:

**Comment by SamLubbers** [comment]
This was implemented again in a new version of the design :100:
