### ISSUE TITLE
Make the role cards full-width on the mobile site

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#96]
## Problem that this feature solves
The role cards seem to have a lot of margin on the sides when viewed in a column on mobile.

## Feature description
We can make the cards wider, so the page looks more balanced.

**Comment by SamLubbers** [comment]
@kajdehoop good suggestion! If you make a pull request with the improved margin I can add directly incorporate it. Like I mentioned in other issues, I'd be useful if in this pull request you add images of before and after.

**Comment by SamLubbers** [comment]
This is fixed with the new design of #168
