### ISSUE TITLE
Add links to navbar

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#97]
## Problem that this feature solves
Right now we only have the (most important) functionality, but it would be nice if people can see some background info or FAQ about the platfom if they want to know more.

## Feature description
We can add a footer with a link to an about page and FAQ page. We can put the feedback button in there, to resolve issue #47.  A footer can also help with a bit of branding, to make the app look more professional and finished.

**Comment by SamLubbers** [comment]
@kajdehoop I agree that we need to add more information, but footers don't work that well in applications that have a feed. I have seen other job pages (like stackoverflow jobs, indeed, google jobs...) and none of them have a footer, instead they keep all relevant information in the navbar or in sidebars. I suggest we follow the design of the XR Global Discourse, which has a set of icons linking to the website and other resources:

![image](https://user-images.githubusercontent.com/15846595/97809327-7d599280-1c6c-11eb-8719-fcd6ee73ab61.png)

**Comment by SamLubbers** [comment]
For now, the only items we would need in the navigation bar are:
* link to the XR NL website
* a question mark icon, leading to a modal or page, where users can read how to give feedback or ask questions
* a login / logout button.

**Comment by kajdehoop** [comment]
Yes that's true. Good idea to first add the basics to the navbar!

**Comment by Upward-Spiral** [comment]
I wanted to start working on this issue, then I realised that the only element missing among the basic ones suggested in Sam's comment is the link to XR NL website. Although the Login and the Language do not really work. I did not find any branches or PRs relating to this issue. 
Is this partially done? Is anyone working on this?

**Comment by SamLubbers** [comment]
@Upward-Spiral welcome to the project! It's great to see you want to help out :heart_eyes: If there is no one assigned and no one left a comment to take up the issue, then it means you can start working on it :ok_hand: 

The only thing missing is indeed the link to the [XR NL website](https://www.extinctionrebellion.nl/). What do you think it's better? If it goes to the home page or to the [about page](https://extinctionrebellion.nl/over-ons/)?

Another thing to take into account is that the link should go to the correct language of the XR NL page. So if a user is browsing the page in english it should go to the english page, and if they're in dutch mode they should go to the dutch page.

**Comment by SamLubbers** [comment]
@Upward-Spiral there is one more thing to take into account. I believe the current navigation bar isn't responsive, so in mobile screens it would exceed the screen width. If you want to add the missing link you can also have a go at making the navigation bar responsive. 

The way it should work is similar to the [XR NL](https://extinctionrebellion.nl/) website: the most important icons still show on mobile screens and the rest of the icons are collapsed into a menu.

**Comment by SamLubbers** [comment]
Updated the title because there is one more thing that we want to add to the navbar: a link to the Github page for this project. We want to add this so that developers who use the platform also know they can help out.

Here there are two design decisions to make:

* which page to link to: home page of the repository, or the contributing guidelines for the project. I think it's best to link to the contributing guidelines because it explains how people can help (rather than how they can install the application)
* how to link to that page. One page is the classic Github icon. However, this might not be clear for non-developers. We could add a "contribute" link, or we could even add the link within the `support` dialog that shows up when clicking on the `support` button

**Comment by kajdehoop** [comment]
I would indeed link to the contributing guidelines, as this is also a good way to make sure people actually read those ;) The support dialog will be removed in favor of the About page (with a Support section). I think the Support section on the About page would be a good place to add the "contribute" link. I'll take it into account in the design of the About page :)
